### ISSUE TITLE
0.10.0

### ISSUE THREAD

**Issue by ghost** [uben0/tree-sitter-typst#16]
Does this project need an update to support 0.10.0?

**Comment by uben0** [comment]
Yes. I read through the version changes and there is one breaking change in the syntax:

The `_` and `*` are considered regular text characters when directly surrounded by alphanumeric characters. But with the 0.10 release, the CJK (Chinese - Japanese - Korean) alphanumeric characters won't be part anymore of this exception.

I have to check the Typst implementation to see what exactly is considered "CJK". Anyway. This parsing will have to be done in the C scanner instead of the `grammar.js`.

Another change to the syntax is the support for other types than strings as dictionary keys. But the grammar already supports any type as dictionary key, so nothing to do for that.

**Comment by uben0** [comment]
I found it [lexer.rs](https://github.com/typst/typst/blob/6808e58a3bb2782c49517c02634b65d85fe28664/crates/typst-syntax/src/lexer.rs#L346)

**Comment by uben0** [comment]
I going to make a program that automatically fetches the files from [unicode.org](https://www.unicode.org/Public/UCD/latest/ucd/) and produces C code with functions testing that a character is part of some unicode set.
